name: Node.js CI #name  

on: #events
  push:
    branches: [ "main", "pipelines"]


jobs: #List of actions
  build-node:
    runs-on:   ubuntu-latest
    container:  node:20
    steps:
      - run:  node  --version
      - uses:  actions/checkout@v3
      - run:  npm ci
      - run:  npm start & npx wait-on http://localhost:3000
