name: Node.js CI

on:
  push:
    branches: [ "main", "pipelines"]

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test  # Add your test command or any other steps you need
